import {
  Ruler,
  Palette,
  Code,
  Download,
  Upload,
  File,
  Folder,
  Briefcase,
  Building,
  Building2,
  Store,
  Warehouse,
  Laptop,
  Monitor,
  Smartphone,
  Tablet,
  Server,
  Database,
  Cloud,
  Wifi,
  Globe,
  LinkIcon,
  Terminal,
  Cpu,
  PenTool,
  Pencil,
  Brush,
  Eraser,
  Figma,
  Layout,
  Grid,
  Layers,
  ImageIcon,
  Camera,
  Video,
  Film,
  Home,
  DoorOpen,
  Lamp,
  Sofa,
  Bed,
  Bath,
  Construction,
  Hammer,
  Wrench,
  Drill,
  Mail,
  Phone,
  MessageCircle,
  Send,
  Share,
  AtSign,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Youtube,
  Github,
  Menu,
  X,
  Check,
  Plus,
  Minus,
  Search,
  Settings,
  Sliders,
  Filter,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ExternalLink,
  Star,
  Heart,
  ThumbsUp,
  Award,
  Trophy,
  Medal,
  Badge,
  Shield,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Clock,
  Calendar,
  Timer,
  Hourglass,
  History,
  RefreshCw,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Receipt,
  Percent,
  User,
  Users,
  UserPlus,
  UserCheck,
  Contact,
  Smile,
  Frown,
  Zap,
  Rocket,
  Target,
  Compass,
  Map,
  MapPin,
  Navigation,
  Flag,
  Bookmark,
  Tag,
  Gift,
  Sparkles,
  Lightbulb,
  Headphones,
  Mic,
  Volume2,
  Music,
  Sun,
  Moon,
  type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  // Layanan & Bisnis
  ruler: Ruler,
  palette: Palette,
  code: Code,
  download: Download,
  upload: Upload,
  file: File,
  folder: Folder,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  store: Store,
  warehouse: Warehouse,

  // Teknologi & Development
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  server: Server,
  database: Database,
  cloud: Cloud,
  wifi: Wifi,
  globe: Globe,
  link: LinkIcon,
  terminal: Terminal,
  cpu: Cpu,

  // Design & Creative
  "pen-tool": PenTool,
  pencil: Pencil,
  brush: Brush,
  eraser: Eraser,
  figma: Figma,
  layout: Layout,
  grid: Grid,
  layers: Layers,
  image: ImageIcon,
  camera: Camera,
  video: Video,
  film: Film,

  // Arsitektur & Konstruksi
  home: Home,
  "door-open": DoorOpen,
  lamp: Lamp,
  sofa: Sofa,
  bed: Bed,
  bath: Bath,
  construction: Construction,
  hammer: Hammer,
  wrench: Wrench,
  drill: Drill,

  // Komunikasi & Sosial
  mail: Mail,
  phone: Phone,
  "message-circle": MessageCircle,
  send: Send,
  share: Share,
  "at-sign": AtSign,
  instagram: Instagram,
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  youtube: Youtube,
  github: Github,

  // Navigasi & UI
  menu: Menu,
  x: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  search: Search,
  settings: Settings,
  sliders: Sliders,
  filter: Filter,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "chevron-down": ChevronDown,
  "external-link": ExternalLink,

  // Status & Feedback
  star: Star,
  heart: Heart,
  "thumbs-up": ThumbsUp,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  badge: Badge,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  "eye-off": EyeOff,

  // Waktu & Kalender
  clock: Clock,
  calendar: Calendar,
  timer: Timer,
  hourglass: Hourglass,
  history: History,
  "refresh-cw": RefreshCw,

  // Keuangan & E-commerce
  "credit-card": CreditCard,
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  package: Package,
  truck: Truck,
  receipt: Receipt,
  percent: Percent,

  // User & People
  user: User,
  users: Users,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  contact: Contact,
  smile: Smile,
  frown: Frown,

  // Lainnya
  zap: Zap,
  rocket: Rocket,
  target: Target,
  compass: Compass,
  map: Map,
  "map-pin": MapPin,
  navigation: Navigation,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  gift: Gift,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  headphones: Headphones,
  mic: Mic,
  "volume-2": Volume2,
  music: Music,
  sun: Sun,
  moon: Moon,
}

interface DynamicIconProps {
  name: string
  color?: string
  size?: number
  className?: string
}

export function DynamicIcon({ name, color = "#313030", size = 24, className = "" }: DynamicIconProps) {
  const iconKey = name?.toLowerCase().trim() || "star"
  const IconComponent = iconMap[iconKey] || Star

  return <IconComponent className={className} color={color} size={size} strokeWidth={1.5} />
}

export { iconMap }
